logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 10.211.55.14 # 主机名
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: hmall # 密码
#    发送者重试
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
#        发送者确认机制
#    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
#    publisher-returns:  # 开启publisher return机制
    publisher-confirm-type: none # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: false # 开启publisher return机制
