logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 10.211.55.14 # 主机名
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: hmall # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        acknowledge-mode: auto
#        retry:
#          enabled: true # 开启消费者失败重试
#          initial-interval: 1000ms # 初识的失败等待时长为1秒
#          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
#          max-attempts: 3 # 最大重试次数
#          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false